host imagenes\vileda0.bmp cm.prm patrones.bd > bases2\vileda\vileda0
host imagenes\vileda1.bmp cm.prm patrones.bd > bases2\vileda\vileda1
host imagenes\vileda2.bmp cm.prm patrones.bd > bases2\vileda\vileda2
host imagenes\vileda3.bmp cm.prm patrones.bd > bases2\vileda\vileda3
host imagenes\vileda4.bmp cm.prm patrones.bd > bases2\vileda\vileda4
host imagenes\vileda5.bmp cm.prm patrones.bd > bases2\vileda\vileda5
host imagenes\vileda6.bmp cm.prm patrones.bd > bases2\vileda\vileda6
host imagenes\vileda7.bmp cm.prm patrones.bd > bases2\vileda\vileda7
host imagenes\vileda8.bmp cm.prm patrones.bd > bases2\vileda\vileda8
host imagenes\vileda9.bmp cm.prm patrones.bd > bases2\vileda\vileda9
