echo "Blanca 2 3 4"
qpccmeuc c:\proyec~1\experim\imagenes\blanca0.bmp cm.prm c:\proyec~1\experim\tanda4\blanca0.bd > experim\tanda4\blanca0.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca1.bmp cm.prm c:\proyec~1\experim\tanda4\blanca1.bd > experim\tanda4\blanca1.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca2.bmp cm.prm c:\proyec~1\experim\tanda4\blanca2.bd > experim\tanda4\blanca2.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca3.bmp cm.prm c:\proyec~1\experim\tanda4\blanca3.bd > experim\tanda4\blanca3.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca4.bmp cm.prm c:\proyec~1\experim\tanda4\blanca4.bd > experim\tanda4\blanca4.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca5.bmp cm.prm c:\proyec~1\experim\tanda4\blanca5.bd > experim\tanda4\blanca5.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca6.bmp cm.prm c:\proyec~1\experim\tanda4\blanca6.bd > experim\tanda4\blanca6.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca7.bmp cm.prm c:\proyec~1\experim\tanda4\blanca7.bd > experim\tanda4\blanca7.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca8.bmp cm.prm c:\proyec~1\experim\tanda4\blanca8.bd > experim\tanda4\blanca8.res
qpccmeuc c:\proyec~1\experim\imagenes\blanca9.bmp cm.prm c:\proyec~1\experim\tanda4\blanca9.bd > experim\tanda4\blanca9.res

