host imagenes\blanca0.bmp cm.prm patrones.bd > bases2\blanca\blanca0
host imagenes\blanca1.bmp cm.prm patrones.bd > bases2\blanca\blanca1
host imagenes\blanca2.bmp cm.prm patrones.bd > bases2\blanca\blanca2
host imagenes\blanca3.bmp cm.prm patrones.bd > bases2\blanca\blanca3
host imagenes\blanca4.bmp cm.prm patrones.bd > bases2\blanca\blanca4
host imagenes\blanca5.bmp cm.prm patrones.bd > bases2\blanca\blanca5
host imagenes\blanca6.bmp cm.prm patrones.bd > bases2\blanca\blanca6
host imagenes\blanca7.bmp cm.prm patrones.bd > bases2\blanca\blanca7
host imagenes\blanca8.bmp cm.prm patrones.bd > bases2\blanca\blanca8
host imagenes\blanca9.bmp cm.prm patrones.bd > bases2\blanca\blanca9
