host imagenes\rayas0.bmp cm.prm patrones.bd > bases2\rayas\rayas0
host imagenes\rayas1.bmp cm.prm patrones.bd > bases2\rayas\rayas1
host imagenes\rayas2.bmp cm.prm patrones.bd > bases2\rayas\rayas2
host imagenes\rayas3.bmp cm.prm patrones.bd > bases2\rayas\rayas3
host imagenes\rayas4.bmp cm.prm patrones.bd > bases2\rayas\rayas4
host imagenes\rayas5.bmp cm.prm patrones.bd > bases2\rayas\rayas5
host imagenes\rayas6.bmp cm.prm patrones.bd > bases2\rayas\rayas6
host imagenes\rayas7.bmp cm.prm patrones.bd > bases2\rayas\rayas7
host imagenes\rayas8.bmp cm.prm patrones.bd > bases2\rayas\rayas8
host imagenes\rayas9.bmp cm.prm patrones.bd > bases2\rayas\rayas9
