host imagenes\baquero0.bmp cm.prm patrones.bd > bases2\baquero\baquero0
host imagenes\baquero1.bmp cm.prm patrones.bd > bases2\baquero\baquero1
host imagenes\baquero2.bmp cm.prm patrones.bd > bases2\baquero\baquero2
host imagenes\baquero3.bmp cm.prm patrones.bd > bases2\baquero\baquero3
host imagenes\baquero4.bmp cm.prm patrones.bd > bases2\baquero\baquero4
host imagenes\baquero5.bmp cm.prm patrones.bd > bases2\baquero\baquero5
host imagenes\baquero6.bmp cm.prm patrones.bd > bases2\baquero\baquero6
host imagenes\baquero7.bmp cm.prm patrones.bd > bases2\baquero\baquero7
host imagenes\baquero8.bmp cm.prm patrones.bd > bases2\baquero\baquero8
host imagenes\baquero9.bmp cm.prm patrones.bd > bases2\baquero\baquero9
